# Generated by Django 4.0.4 on 2022-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=36)),
                ('lastName', models.CharField(max_length=36)),
                ('email', models.EmailField(max_length=36)),
                ('contact', models.CharField(max_length=36)),
                ('intrestedSubject', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=36)),
                ('lastName', models.CharField(max_length=36)),
                ('username', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=36)),
                ('userType', models.CharField(choices=[(1, 'Admin'), (2, 'User')], max_length=36)),
            ],
        ),
    ]
