# Generated by Django 4.0.4 on 2022-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_inquiry_intrestedsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=36),
        ),
    ]
