# Generated by Django 4.0.4 on 2022-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='intrestedSubject',
            field=models.CharField(choices=[('M', 'Maths'), ('P', 'Physics'), ('C', 'Chemistry')], max_length=36),
        ),
    ]
